### ISSUE TITLE
屏蔽的hosts域名会阻止新固件升级

### ISSUE THREAD

**Issue by temurlee** [luckydzp/skip-mdm#2]
#block mdm connect
0.0.0.0 iprofiles.apple.com
0.0.0.0 mdmenrollment.apple.com
0.0.0.0 deviceenrollment.apple.com
0.0.0.0 gdmf.apple.com
0.0.0.0 acmdm.apple.com
0.0.0.0 albert.apple.com

---------

应该是这条URL会影响？或许可以不必屏蔽这条？
0.0.0.0 gdmf.apple.com

**Comment by luckydzp** [comment]
<img width="609" alt="image" src="https://github.com/luckydzp/skip-mdm/assets/3041197/e3c58581-c6d6-4f85-871f-3fe8d71bb520">
并不影响哦，不过最好是不要升级到14吧，14如果出现弹窗是全屏弹窗。13完全正常使用，没有出现过任何提示。没有必要升级。公司用的14，差别不大。
